services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    networks:
      - app-network

networks:
  app-network:
    external: true
